version: '3.9'
services:
  moslib-front:
    image: "cr.yandex/${YC_CONTAINER_REGISTRY_ID}/moslib-frontend:latest"
    build: 
      dockerfile: Dockerfile
      context: ./frontend/
    container_name: moslib-front
    ports:
      - "80:80"
    networks:
      - moslib-recsys

  moslib-backend:
    image: "cr.yandex/${YC_CONTAINER_REGISTRY_ID}/moslib-backend:latest"
    build: 
      dockerfile: Dockerfile
      context: ./backend/
    container_name: moslib-backend
    networks:
      - moslib-recsys
    depends_on:
      - moslib-db
    env_file: 
      - .env
      -
  moslib-db:
    image: "cr.yandex/${YC_CONTAINER_REGISTRY_ID}/moslib-db:latest"
    build:
      dockerfile: Dockerfile
      context: ./db/
    container_name: moslib-db
    hostname: moslib-db
    ports:
      - "5432:5432"
    volumes:
      - .storage:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - moslib-recsys

  moslib-fit:
    image: "cr.yandex/${YC_CONTAINER_REGISTRY_ID}/moslib-backend:latest"
    build:
      dockerfile: Dockerfile
      context: ./backend/
    container_name: moslib-backend
    command:
      - "python app/scripts/train_model.py"
    networks:
      - moslib-recsys
    depends_on:
      - moslib-db
    env_file:
      - .env

  moslib-predict:
    image: "cr.yandex/${YC_CONTAINER_REGISTRY_ID}/moslib-backend:latest"
    build:
      dockerfile: Dockerfile
      context: ./backend/
    container_name: moslib-backend
    command:
      - "python app/scripts/generate_predictions.py"
    networks:
      - moslib-recsys
    depends_on:
      - moslib-db
    env_file:
      - .env

networks:
  moslib-recsys:
    external: true
    name: moslib-recsys