version: "3.9"
services:
  moslib-npm:
    build: 
      dockerfile: .dev/Dockerfile
      context: ../.
    ports:
      - "3000:3000"
    container_name: moslib-npm
    volumes:
      - '../package.json:/app/package.json'
      - '../build:/app/build'
      - '../src:/app/src'
      - '../public:/app/public'
    networks:
      - moslib-recsys
    # command: "npm run watch"

networks:
  moslib-recsys:
    external: true
    name: moslib-recsys