default_context:
  project_name: 'moslib'
  project_slug: 'moslib'
  domain_main: 'lay-on-l10n.ru'
  domain_staging: 'stag.lay-on-l10n.ru'
  docker_swarm_stack_name_main: 'lay-on-l10n-ru'
  docker_swarm_stack_name_staging: 'stag-lay-on-l10n-ru'
  secret_key: '9c735a1bb27593f2deb0852e37925a37eae9c6e95ef59cee9acfaa7aec4edace'
  first_superuser: 'admin'
  first_superuser_password: 'l@yonliionforever'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.lay-on-l10n.ru", "https://stag.lay-on-l10n.ru", "https://lay-on-l10n.ru", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@lay-on-l10n.ru'
  postgres_password: 'quee9ahpei6Mi'
  pgadmin_default_user: 'pgadmin'
  pgadmin_default_user_password: 'quee9ahpei6Mi'
  traefik_constraint_tag: 'moslib'
  traefik_constraint_tag_staging: 'stag.lay-on-l10n.ru'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:l@yonliionforever'
  sentry_dsn: ''
  docker_image_prefix: 'moslib_'
  docker_image_backend: 'moslib_backend'
  docker_image_celeryworker: 'moslib_celeryworker'
  docker_image_frontend: 'moslib_frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
